from __future__ import annotations

import yaml

from app.models import AreaConfig, BridgeConfig, GenerationResult, ResolvedEntity

# Maximum entities per HomeKit bridge
HOMEKIT_ENTITY_LIMIT = 150

# Maximum bridge name length
MAX_BRIDGE_NAME_LENGTH = 25


def generate_homekit_yaml(
    area_configs: list[AreaConfig],
    area_entities: dict[str, list[ResolvedEntity]],
    start_port: int,
) -> GenerationResult:
    """
    Generate HomeKit YAML configuration from user area configs.

    Always uses include_entities (not include_domains) because HomeKit's
    include_domains is global, not per-bridge.
    """
    bridges: list[BridgeConfig] = []
    warnings: list[str] = []
    used_names: set[str] = set()
    port = start_port

    for config in area_configs:
        if not config.enabled:
            continue

        entities = area_entities.get(config.area_id, [])

        # Filter to HomeKit-supported, non-disabled, non-hidden, non-diagnostic
        candidates = [
            e for e in entities
            if e.homekit_supported
            and not e.disabled
            and not e.hidden
            and e.entity_category is None
        ]

        # Apply mode-specific filtering
        if config.mode == "all_domains":
            included = [e.entity_id for e in candidates]
        elif config.mode == "selected_domains":
            domain_set = set(config.include_domains)
            included = [e.entity_id for e in candidates if e.domain in domain_set]
        elif config.mode == "manual":
            included_set = set(config.include_entities)
            included = [
                e.entity_id for e in candidates if e.entity_id in included_set
            ]
        else:
            included = [e.entity_id for e in candidates]

        # Apply exclusions
        excluded_set = set(config.exclude_entities)
        final_included = [eid for eid in included if eid not in excluded_set]
        final_excluded = sorted(
            eid for eid in config.exclude_entities
            if eid in {e.entity_id for e in candidates} and eid in set(included)
        )

        # Unique name
        name = _unique_name(config.bridge_name, used_names)
        used_names.add(name)

        # Entity limit warning
        if len(final_included) > HOMEKIT_ENTITY_LIMIT:
            warnings.append(
                f"Bridge '{name}' has {len(final_included)} entities "
                f"(HomeKit limit is {HOMEKIT_ENTITY_LIMIT})"
            )

        filter_dict: dict[str, list[str]] = {
            "include_entities": sorted(final_included),
        }
        if final_excluded:
            filter_dict["exclude_entities"] = sorted(final_excluded)

        bridge = BridgeConfig(
            name=name,
            port=port,
            mode="bridge",
            filter=filter_dict,
        )
        bridges.append(bridge)
        port += 1

    # Generate YAML
    yaml_content = _render_yaml(bridges)

    return GenerationResult(
        yaml_content=yaml_content,
        bridges=bridges,
        warnings=warnings,
        entity_count_per_bridge={
            b.name: len(b.filter["include_entities"]) for b in bridges
        },
    )


def _unique_name(name: str, used_names: set[str]) -> str:
    """Ensure bridge name is unique and within length limits."""
    # Truncate to max length
    if len(name) > MAX_BRIDGE_NAME_LENGTH:
        name = name[:MAX_BRIDGE_NAME_LENGTH].rstrip()

    # Strip invalid characters (keep alphanumeric, spaces, hyphens)
    name = "".join(c for c in name if c.isalnum() or c in " -")
    name = name.strip()

    if not name:
        name = "Bridge"

    # De-duplicate
    if name not in used_names:
        return name

    suffix = 2
    while f"{name} {suffix}" in used_names:
        suffix += 1

    candidate = f"{name} {suffix}"
    # Re-truncate if suffix pushed over limit
    if len(candidate) > MAX_BRIDGE_NAME_LENGTH:
        trimmed = name[: MAX_BRIDGE_NAME_LENGTH - len(f" {suffix}")]
        candidate = f"{trimmed} {suffix}"

    return candidate


def _render_yaml(bridges: list[BridgeConfig]) -> str:
    """Render bridges to YAML string with a header comment."""
    if not bridges:
        return "# Auto-generated by HomeKit Area Bridge\n# No bridges configured\n"

    yaml_data = {
        "homekit": [
            {
                "name": b.name,
                "port": b.port,
                "mode": b.mode,
                "filter": b.filter,
            }
            for b in bridges
        ]
    }

    header = (
        "# Auto-generated by HomeKit Area Bridge\n"
        "# Do not edit manually - changes will be overwritten\n\n"
    )
    body = yaml.dump(yaml_data, default_flow_style=False, sort_keys=False)
    return header + body
